### ISSUE TITLE
Incorrect response to invalid command

### ISSUE THREAD

**Issue by teikjun** [AY1920S2-CS2103T-W16-3/main#48]
**How to reproduce the bug:**
1. Type an invalid command into the command box. 
2. The incorrect command message is not shown. The command box text prompt is not cleared.

**Information about the bug:**
In the Intellij run window, the following errors are shown.
java.lang.reflect.InvocationTargetException
java.lang.NullPointerException is thrown

**Comment by wyt-sonia** [comment]
Thanks for raising the issue, and I'll look at it soon.

**Comment by wyt-sonia** [comment]
The bug is fixed, thus I'll close the issue.
