### ISSUE TITLE
Problem with loading json file 

### ISSUE THREAD

**Issue by teikjun** [AY1920S2-CS2103T-W16-3/main#49]
**How to reproduce the bug:**
1. Start the program
2. The sample tasks in SampleDataUtil.java are not loaded

**Information about the bug:**
In the intelliJ window, the following errors are logged:
Error reading from jsonFile file data\addressbook.json: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class seedu.address.storage.JsonSerializableAddressBook] value failed (java.lang.NullPointerException): null
Data file not in the correct format. Will be starting with an empty AddressBook

**Comment by gx-huang** [comment]
You might want to delete the file in main/data before starting up AddressBook. Sample data is only loaded if that directory's empty iirc

https://nus-cs2103-ay1920s2.github.io/addressbook-level3/tutorials/AddRemark#updating-storage
